---
abstract: 'Connect perl data structures to Redis'
author:
  - 'David Leadbeater <dgl@dgl.cx>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Tie-Redis
requires:
  AnyEvent::Redis: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Tie-Redis
  repository: git://github.com/dgl/Tie-Redis
version: 0.2
